spring.application.name=test

server.port:8088
server.address=0.0.0.0
server.servlet.context-path=/myapp

spring.datasource.url=jdbc:sqlserver://yourleague.database.windows.net:1433;database=yourleaguedb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=erhamdb
spring.datasource.password=Yourleague123#
# Log SQL statements
logging.level.org.hibernate.SQL=DEBUG

# Log the parameter binding values (for Hibernate 6+)
logging.level.org.hibernate.orm.jdbc.bind=TRACE   

# Removed explicit dialect to let Hibernate auto-detect based on the JDBC driver/metadata
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql: true

security.basic.enable: false
security.ignored=/**